execute pathogen#infect()
syntax on
filetype plugin indent on

let g:airline#extensions#tabline#enabled = 1
let g:ansible_options = {'ignore_blank_lines': 0}

" Always show statusline
set laststatus=2

" Use 256 colours (Use this setting only if your terminal supports 256 colours)
set t_Co=256
