# Nrpe variables
nagios_nrpe_server_pid: /var/run/nagios/nrpe.pid
nagios_nrpe_server_user: nagios
nagios_nrpe_server_group: nagios
nagios_nrpe_server_service: nagios-nrpe-server
nagios_nrpe_server_plugins_dir: /usr/lib/nagios/plugins
nagios_nrpe_server_dir: /etc/nagios
nagios_nrpe_server_bind_address: 127.0.0.1
nagios_nrpe_server_port: 5666
nagios_nrpe_server_allowed_hosts: 31.12.66.38
nagios_nrpe_server_allowed_hosts_lan: 192.168.66.38

# Ssh public variables
# Add key you want after using same syntax and put your public key in the files folder of this roles
ssh_users:
  - name: root
    key: "{{ lookup('file', 'sshroot.pub') }}"
  #- name: exemple
  #  key: ...
